bibliography:book.bib
#+BEGIN_SRC emacs-lisp
(load-file "./elisp.el")
#+END_SRC 

#+RESULTS:
: t

cite:elb05:30

Some [[linktype:elb05][p.22]] links [[linktype:elb05][p.23]] embedded [[linktype:elb05][p.24]] in [[linktype:elb05][p.25]] a [[linktype:xee2019][p.2]] 

a a a baa ba ba aa aba a 

I wanted to get baptised. Do I just want to make my christian friends happy?
Only wanting to make my friends happy I believe is not enough of a reason to do it, if it's a reason at all. 
I get great encouragement from the people of my church. We sing together, raise our arms in the air, sometimes the elder people shout or say things during praise or the sermon. We speak to each other, touching each other on the shoulder while speaking from the heart (truly) about what we want for them and what sometimes even about what we see in their future. It helps me to have a bit of information about the person you are praying for (aloud, and next to or in front of them.). Once (it was the second time our parish met for a prolonged weekend) there was a man who I didn't know standing next to me, and I started praying for him, not knowing anything about his life. I spoke mostly about general things, things that could apply to anyone. I don't know if he appreciated what I said, or if it fit at all into his life. I started praying for him out of a planned impulse. 
Earlier during that praise session, I prayed for the woman on my left, who I know, and I knew what her situation in life was back then, at least to some degree. Among other things, I said to her 'I want to bless you with great love, and god's love, who imparts it onto you [...]'. I didn't intend to predict or announce a love I would be imparting on her, and specifically, I didn't want to refer to the romantic meaning of the word. I think I told her that she will become a great teacher, and will have fun at her job, she will rejoice in God's company, even in hard times, when everybody seems to turn on her.' Looking back on that, the first bit is risky, because it is a prediction about somebody else's future. Generally, I am trying to only write down the things that are relatively save to say about others, and I am trying to not mention their real names or give too much away about their lives, if they didn't specifically agree that I could do so. But not revealing things I will weigh against the power of the associated story, so that the most important and interesting things I will definitely write about. 

Now back to the question of wether or not I am only trying to optimize the dynamic among the people in the parish by going along with and and even energizing what is being done there, which I do.

If there is nobody speaking out loud, I sometimes am brave enough to step up. I did it there, and it filled my body with emotion and made me tremble.

It wasn't like I stood up during the praise session and went to some completely different person in the room who I felt needed it. 
I did that afterwards, since I knew somebody who I knew that he could use it.

I do go up to people whom I know things about and I pray for them about the things I know. But also once I went up to somebody and told him not always so general things about his life, assuming things without knowing if it would apply in his life. And prior to starting to pray I also didn't know what I would say. That readiness and courage seems magical to me, but it's not necessarily so.

* ** Am I truthful to my friends when someone is asking weather I communicate with god?
I said that I have had an exchange of information with god happen. For example: 

- He speaks to me through the words in the bible, I am the one reading the bible, and I see great wisdom in what it says (that's one-way communication)

- I put all my trust in him in moments when I see my powerlessness, and he lifts me right up and brings me back my joy. Without my understanding of the christian god, I would have not had that feeling, and it was of great benefit, it allowed me to go on with sorrow lifted from my shoulders. (that was two-way communication)

- He commands us to pray for each other []. Every time I do this, it brings me closer to him (emotionally, not necessarily intellectually). When I collect the courage to do what he commands, then do it, and that is met with a positive response, it brings me closer to him. It's never really been met with a negative response.

** What does it do with me when somebody like Richard Dawkins says that religion is harmful?
It makes me ask if he had the chance and was willing to experience it (christianity as I understand it) and to immerse himself in it, making sacrifices to get closer to finding out for himself, if god exists or if not. If unlocking that set values combined with belief is worth enough in our world not be there (if god turns out to not exist, but we still get the chance to evaluate life after we are done living it, looking back you could say that believers were incorrect in thinking there was a god). 

** What if that what I would now interpret as an act of god, in fact will be explainable in the future? Does it then lose it's meaning?
What in the past was often described as magic (thunder, clouds, the stars), can in many cases be explained and simulated now, using the tools of mathematics, logic and our ability to make abstractions and categorizations and build theoretic models that are backed up by experimental evidence in accordance with the scientific method. Science relies on observations and mathematics to build a model that reproduces these observations, where the substructural axioms of that model are always chosen to be as simple as possible. 
