#+LATEX_HEADER: \addbibresource{bibliography.bib} 
#+LATEX_HEADER: \addbibresource{test.bib} 

* klin - functionality for my science writing workflow
** misc notes
The name /klin/ is a one-step rotation of the word /link/. 
This emacs-lisp library provides functions to /link/ together and integrate tools to as conveniently as possible link together all produced documents during e.g. lectures, and alongside that, to integrate all other side notes/exercises directly from the cloud into an org-mode document (e.g. after taking a picture/scanning a document with your phone camera). 

I intend to do all structuring of arguments/researching of topics in e-books from within emacs, so this library implements some functions to make quick browsing and comparing of a number of pdf documents easy.

Imagine a tabbed pdf viewer (much like in a browser) together with the ability to via simple key commands make cross-references encoded in plain text, and pull together all your sources into an org-mode document to produce some structured writing about the problem at hand, all in one place, pulling together all the information necessary and making it accessible inside a powerful dynamic environment like emacs.

So far, my workflow relies on a few specific packages, among them are elscreen, pdf-tools, org-ref and org-noter. 

** TODO:
- debug the system by trying to get some work done
- make a command that lets you select two newly created pdfs scans, display them side by side for you to check, then makes one temporary file out of them using
#+BEGIN_SRC sh
pdftk A=odd.pdf B=even.pdf shuffle A B output collated_pages.pdf
#+END_SRC
  lets you check it and then lets you save it as a non-temporary file in the scanner folder and simultaneously moves the the two seperate pdfs to trash. 
- make an integrated workflow to annotate any linked pdf using xournal, so that scanned-in images can be corrected/annotated digitally with e.g. a graphic tablet if necessary.
- make a graphical pdf editing tool in emacs using pdf-view-mode
- make a list of features in this README
- (low importance) make your custom org link to more seamlessly integrate with org-mode of cross-linking to referenced pdfs

